// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enwrjtqflzrqnzzllqua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVud3JqdHFmbHpycW56emxscXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjczODQsImV4cCI6MjA2NDMwMzM4NH0.dt0aXB5Ct1ceBtN1BGycc4blvvybloV3yLLSuOr_v9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);